# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paneladmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(923, 708)
        Form.setMinimumSize(QtCore.QSize(480, 435))
        Form.setMaximumSize(QtCore.QSize(213456, 2134567))
        Form.setStyleSheet("font: 87 22pt \"Arial Black\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-210, -950, 1411, 1881))
        self.label.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.add_new_student_btn = QtWidgets.QPushButton(Form)
        self.add_new_student_btn.setGeometry(QtCore.QRect(21, 91, 411, 60))
        self.add_new_student_btn.setMinimumSize(QtCore.QSize(30, 60))
        self.add_new_student_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_new_student_btn.setMouseTracking(False)
        self.add_new_student_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.add_new_student_btn.setObjectName("add_new_student_btn")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 441, 621))
        self.label_5.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(280, 20, 411, 51))
        self.name_label.setObjectName("label_2")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(20, 600, 151, 61))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exit_btn.setMouseTracking(False)
        self.exit_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/left-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(50, 40))
        self.exit_btn.setObjectName("exit_btn")
        self.add_new_teacher_btn = QtWidgets.QPushButton(Form)
        self.add_new_teacher_btn.setGeometry(QtCore.QRect(21, 158, 411, 60))
        self.add_new_teacher_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.add_new_teacher_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_new_teacher_btn.setMouseTracking(False)
        self.add_new_teacher_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.add_new_teacher_btn.setObjectName("add_new_teacher_btn")
        self.add_new_class_btn = QtWidgets.QPushButton(Form)
        self.add_new_class_btn.setGeometry(QtCore.QRect(21, 225, 411, 60))
        self.add_new_class_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.add_new_class_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_new_class_btn.setMouseTracking(False)
        self.add_new_class_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.add_new_class_btn.setObjectName("add_new_class_btn")
        self.delete_student_btn = QtWidgets.QPushButton(Form)
        self.delete_student_btn.setGeometry(QtCore.QRect(21, 292, 411, 60))
        self.delete_student_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.delete_student_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.delete_student_btn.setMouseTracking(False)
        self.delete_student_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.delete_student_btn.setObjectName("delete_student_btn")
        self.delete_teacher_btn = QtWidgets.QPushButton(Form)
        self.delete_teacher_btn.setGeometry(QtCore.QRect(21, 359, 411, 60))
        self.delete_teacher_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.delete_teacher_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.delete_teacher_btn.setMouseTracking(False)
        self.delete_teacher_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.delete_teacher_btn.setObjectName("delete_teacher_btn")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(480, 80, 431, 621))
        self.scrollArea.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-color: rgb(199, 183, 164);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 619))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QVBoxLayout()
        self.scrollAreaWidgetContents.setLayout(self.scrollAreaLayout)
#         self.sample = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
#         self.sample.setGeometry(QtCore.QRect(10, 10, 410, 60))
#         self.sample.setMinimumSize(QtCore.QSize(30, 60))
#         self.sample.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
#         self.sample.setMouseTracking(False)
#         self.sample.setStyleSheet("QPushButton:hover{\n"
# "font: 16pt \"Arial\";\n"
# "color: rgb(255, 255, 255);\n"
# "    background-color: rgb(193, 0, 0);\n"
# "border-radius: 10px;\n"
# "}\n"
# "\n"
# "QPushButton{\n"
# "font: 16pt \"Arial\";\n"
# "color: rgb(255, 255, 255);\n"
# "background-color: rgb(139, 0, 0);\n"
# "border-radius: 10px;\n"
# "}\n"
# "QPushButton:pressed{\n"
# "font: 16pt \"Arial\";\n"
# "color: rgb(0, 0, 0);\n"
# "    background-color: rgb(225, 100, 100);\n"
# "border-radius: 10px;\n"
# "}")
#         self.sample.setObjectName("sample")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.connect_chat_btn = QtWidgets.QPushButton(Form)
        self.connect_chat_btn.setGeometry(QtCore.QRect(21, 493, 411, 60))
        self.connect_chat_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.connect_chat_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.connect_chat_btn.setMouseTracking(False)
        self.connect_chat_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.connect_chat_btn.setObjectName("connect_chat_btn")
        self.delete_class_btn = QtWidgets.QPushButton(Form)
        self.delete_class_btn.setGeometry(QtCore.QRect(21, 426, 411, 60))
        self.delete_class_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.delete_class_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.delete_class_btn.setMouseTracking(False)
        self.delete_class_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.delete_class_btn.setObjectName("delete_class_btn")
        self.label.raise_()
        self.label_5.raise_()
        self.name_label.raise_()
        self.exit_btn.raise_()
        self.add_new_student_btn.raise_()
        self.add_new_teacher_btn.raise_()
        self.add_new_class_btn.raise_()
        self.delete_student_btn.raise_()
        self.scrollArea.raise_()
        self.connect_chat_btn.raise_()
        self.delete_class_btn.raise_()
        self.delete_teacher_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_new_student_btn.setText(_translate("Form", "Добавить нового ученика"))
        self.name_label.setText(_translate("Form", "Панель управления"))
        self.add_new_teacher_btn.setText(_translate("Form", "Добавить нового учителя"))
        self.add_new_class_btn.setText(_translate("Form", "Добавить новый класс"))
        self.delete_student_btn.setText(_translate("Form", "Удалить ученика"))
        self.delete_teacher_btn.setText(_translate("Form", "Удалить учителя"))
        # self.sample.setText(_translate("Form", "Главная группа"))
        self.connect_chat_btn.setText(_translate("Form", "Подключиться к группе"))
        self.delete_class_btn.setText(_translate("Form", "Удалить класс"))
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
