# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newclass.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import new_rc

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 435)
        Form.setMinimumSize(QtCore.QSize(480, 435))
        Form.setMaximumSize(QtCore.QSize(480, 2134567))
        Form.setStyleSheet("font: 87 22pt \"Arial Black\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-400, -570, 1411, 1401))
        self.label.setStyleSheet("background-image: url(new_rc/1627100073_16-kartinkin-com-p-bezhevii-geometricheskii-fon-krasivo-17);")
        # self.label.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.create_btn = QtWidgets.QPushButton(Form)
        self.create_btn.setGeometry(QtCore.QRect(310, 350, 151, 61))
        self.create_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.create_btn.setMouseTracking(False)
        self.create_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.create_btn.setObjectName("create_btn")
        self.class_letter_input = QtWidgets.QLineEdit(Form)
        self.class_letter_input.setGeometry(QtCore.QRect(180, 120, 251, 31))
        self.class_letter_input.setStyleSheet("font: 14pt \"Arial\";")
        self.class_letter_input.setText("")
        self.class_letter_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.class_letter_input.setObjectName("class_letter_input")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 151, 51))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 451, 251))
        self.label_5.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 411, 51))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 161, 51))
        self.label_6.setStyleSheet("font: 14pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 161, 51))
        self.label_7.setStyleSheet("font: 14pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.class_num_input = QtWidgets.QLineEdit(Form)
        self.class_num_input.setGeometry(QtCore.QRect(180, 190, 251, 31))
        self.class_num_input.setStyleSheet("font: 14pt \"Arial\";")
        self.class_num_input.setObjectName("class_num_input")
        self.unical_id_class_input = QtWidgets.QLineEdit(Form)
        self.unical_id_class_input.setGeometry(QtCore.QRect(180, 260, 251, 31))
        self.unical_id_class_input.setStyleSheet("font: 14pt \"Arial\";")
        self.unical_id_class_input.setText("")
        self.unical_id_class_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.unical_id_class_input.setObjectName("unical_id_class_input")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(20, 350, 151, 61))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exit_btn.setMouseTracking(False)
        self.exit_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/left-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(50, 40))
        self.exit_btn.setObjectName("exit_btn")
        self.label.raise_()
        self.create_btn.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.class_letter_input.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.class_num_input.raise_()
        self.unical_id_class_input.raise_()
        self.exit_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_btn.setText(_translate("Form", "Добавить"))
        self.label_4.setText(_translate("Form", "Буква класса:"))
        self.label_2.setText(_translate("Form", "Новый класс"))
        self.label_6.setText(_translate("Form", "Индекс класса:"))
        self.label_7.setText(_translate("Form", "Уникальный id:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
