# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 650)
        Form.setMaximumSize(QtCore.QSize(900, 650))
        Form.setStyleSheet("font: 14pt \"Arial\";")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 70, 871, 511))
        self.scrollArea.setMinimumSize(QtCore.QSize(725, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 161, 51))
        self.label_2.setStyleSheet("background-color: rgb(245, 198, 190);\n"
"border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(60, 220, 171, 51))
        self.label_3.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bk = QtWidgets.QLabel(Form)
        self.bk.setGeometry(QtCore.QRect(-50, -10, 1031, 761))
        self.bk.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.bk.setText("")
        self.bk.setObjectName("bk")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(740, 10, 70, 50))
        self.exit_btn.setMinimumSize(QtCore.QSize(70, 50))
        self.exit_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exit_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/home (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(30, 40))
        self.exit_btn.setObjectName("exit_btn")
        self.name_user = QtWidgets.QLabel(Form)
        self.name_user.setGeometry(QtCore.QRect(80, 20, 321, 41))
        self.name_user.setText("")
        self.name_user.setObjectName("name_user")
        self.menu_btn = QtWidgets.QPushButton(Form)
        self.menu_btn.setGeometry(QtCore.QRect(820, 10, 70, 50))
        self.menu_btn.setMinimumSize(QtCore.QSize(70, 50))
        self.menu_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/premium-icon-group-4155625 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_btn.setIcon(icon1)
        self.menu_btn.setIconSize(QtCore.QSize(30, 40))
        self.menu_btn.setObjectName("menu_btn")
        self.name_other_user = QtWidgets.QLabel(Form)
        self.name_other_user.setGeometry(QtCore.QRect(440, 20, 281, 41))
        self.name_other_user.setObjectName("name_other_user")
        self.login_txt = QtWidgets.QLabel(Form)
        self.login_txt.setGeometry(QtCore.QRect(20, 20, 50, 41))
        self.login_txt.setMinimumSize(QtCore.QSize(50, 0))
        self.login_txt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.login_txt.setObjectName("login_txt")
        self.btn_send = QtWidgets.QPushButton(Form)
        self.btn_send.setGeometry(QtCore.QRect(820, 590, 70, 40))
        self.btn_send.setMinimumSize(QtCore.QSize(70, 40))
        self.btn_send.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_send.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.btn_send.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/send-button_icon-icons.com_72565 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_send.setIcon(icon2)
        self.btn_send.setIconSize(QtCore.QSize(30, 30))
        self.btn_send.setObjectName("btn_send")
        self.send_area = QtWidgets.QLineEdit(Form)
        self.send_area.setGeometry(QtCore.QRect(20, 595, 791, 35))
        self.send_area.setMinimumSize(QtCore.QSize(30, 35))
        self.send_area.setStyleSheet("font: 75 14pt \"Arial\";")
        self.send_area.setObjectName("send_area")
        self.bk.raise_()
        self.name_user.raise_()
        self.scrollArea.raise_()
        self.menu_btn.raise_()
        self.name_other_user.raise_()
        self.login_txt.raise_()
        self.btn_send.raise_()
        self.send_area.raise_()
        self.exit_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "учитель"))
        self.label_3.setText(_translate("Form", "ученик"))
        self.name_other_user.setText(_translate("Form", "Переписка:"))
        self.login_txt.setText(_translate("Form", "Имя:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
