# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'techdell.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 395)
        Form.setMinimumSize(QtCore.QSize(480, 395))
        Form.setMaximumSize(QtCore.QSize(480, 395))
        Form.setStyleSheet("font: 87 22pt \"Arial Black\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-980, -980, 2141, 1961))
        self.label.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.del_btn = QtWidgets.QPushButton(Form)
        self.del_btn.setGeometry(QtCore.QRect(310, 320, 151, 61))
        self.del_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.del_btn.setMouseTracking(False)
        self.del_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.del_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/bin (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.del_btn.setIcon(icon)
        self.del_btn.setIconSize(QtCore.QSize(50, 40))
        self.del_btn.setObjectName("del_btn")
        self.unical_code_input = QtWidgets.QLineEdit(Form)
        self.unical_code_input.setGeometry(QtCore.QRect(310, 120, 121, 31))
        self.unical_code_input.setStyleSheet("font: 14pt \"Arial\";")
        self.unical_code_input.setText("")
        self.unical_code_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.unical_code_input.setObjectName("unical_code_input")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 281, 51))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 451, 221))
        self.label_5.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 411, 51))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 431, 51))
        self.label_6.setStyleSheet("font: 75 16pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.delete_admin_password_input = QtWidgets.QLineEdit(Form)
        self.delete_admin_password_input.setGeometry(QtCore.QRect(30, 240, 401, 31))
        self.delete_admin_password_input.setStyleSheet("font: 14pt \"Arial\";")
        self.delete_admin_password_input.setText("")
        self.delete_admin_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.delete_admin_password_input.setObjectName("delete_admin_password_input")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(10, 320, 151, 61))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exit_btn.setMouseTracking(False)
        self.exit_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.exit_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/left-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn.setIcon(icon1)
        self.exit_btn.setIconSize(QtCore.QSize(50, 40))
        self.exit_btn.setObjectName("exit_btn")
        self.label.raise_()
        self.del_btn.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.unical_code_input.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.delete_admin_password_input.raise_()
        self.exit_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Уникальный код учителя:"))
        self.label_2.setText(_translate("Form", "Удаление учителя"))
        self.label_6.setText(_translate("Form", "Введите пароль администратора:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
