# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enteradmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 435)
        Form.setMinimumSize(QtCore.QSize(480, 435))
        Form.setMaximumSize(QtCore.QSize(480, 435))
        Form.setStyleSheet("font: 87 22pt \"Arial Black\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-180, -630, 1411, 1331))
        self.label.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.enter_btn_admin = QtWidgets.QPushButton(Form)
        self.enter_btn_admin.setGeometry(QtCore.QRect(320, 350, 151, 61))
        self.enter_btn_admin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.enter_btn_admin.setMouseTracking(False)
        self.enter_btn_admin.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.enter_btn_admin.setObjectName("enter_btn_admin")
        self.enter_password_admin = QtWidgets.QLineEdit(Form)
        self.enter_password_admin.setGeometry(QtCore.QRect(130, 250, 301, 31))
        self.enter_password_admin.setStyleSheet("font: 14pt \"Arial\";")
        self.enter_password_admin.setText("")
        self.enter_password_admin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.enter_password_admin.setObjectName("enter_password_admin")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 121, 51))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.enter_login_admin = QtWidgets.QLineEdit(Form)
        self.enter_login_admin.setGeometry(QtCore.QRect(130, 180, 301, 31))
        self.enter_login_admin.setStyleSheet("font: 14pt \"Arial\";")
        self.enter_login_admin.setObjectName("enter_login_admin")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 451, 181))
        self.label_5.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.main_label = QtWidgets.QLabel(Form)
        self.main_label.setGeometry(QtCore.QRect(10, 40, 471, 51))
        self.main_label.setObjectName("main_label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 121, 51))
        self.label_3.setStyleSheet("font: 14pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.return_btn_admin = QtWidgets.QPushButton(Form)
        self.return_btn_admin.setGeometry(QtCore.QRect(30, 350, 151, 61))
        self.return_btn_admin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.return_btn_admin.setMouseTracking(False)
        self.return_btn_admin.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.return_btn_admin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/left-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.return_btn_admin.setIcon(icon)
        self.return_btn_admin.setIconSize(QtCore.QSize(50, 40))
        self.return_btn_admin.setObjectName("return_btn_admin")
        self.label.raise_()
        self.enter_btn_admin.raise_()
        self.label_5.raise_()
        self.main_label.raise_()
        self.label_3.raise_()
        self.enter_login_admin.raise_()
        self.enter_password_admin.raise_()
        self.label_4.raise_()
        self.return_btn_admin.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enter_btn_admin.setText(_translate("Form", "Войти"))
        self.label_4.setText(_translate("Form", "Пароль:"))
        self.main_label.setText(_translate("Form", "Вход администратора"))
        self.label_3.setText(_translate("Form", "Логин:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
