# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 435)
        Form.setMinimumSize(QtCore.QSize(480, 435))
        Form.setMaximumSize(QtCore.QSize(480, 435))
        Form.setStyleSheet("font: 87 22pt \"Arial Black\";")
        self.bk_img = QtWidgets.QLabel(Form)
        self.bk_img.setGeometry(QtCore.QRect(-190, -630, 1491, 1201))
        self.bk_img.setStyleSheet("background-image: url(:/newPrefix/123456tyhgb);")
        self.bk_img.setText("")
        self.bk_img.setObjectName("bk_img")
        self.main_label = QtWidgets.QLabel(Form)
        self.main_label.setGeometry(QtCore.QRect(190, 40, 121, 51))
        self.main_label.setObjectName("main_label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 121, 51))
        self.label_3.setStyleSheet("font: 14pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.enter_login = QtWidgets.QLineEdit(Form)
        self.enter_login.setGeometry(QtCore.QRect(130, 170, 301, 31))
        self.enter_login.setStyleSheet("font: 14pt \"Arial\";")
        self.enter_login.setObjectName("enter_login")
        self.enter_password = QtWidgets.QLineEdit(Form)
        self.enter_password.setGeometry(QtCore.QRect(130, 240, 301, 31))
        self.enter_password.setStyleSheet("font: 14pt \"Arial\";")
        self.enter_password.setText("")
        self.enter_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.enter_password.setObjectName("enter_password")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 121, 51))
        self.label_4.setStyleSheet("font: 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 451, 181))
        self.label_5.setStyleSheet("background-color: rgb(247, 227, 203);\n"
"border-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.enter_btn = QtWidgets.QPushButton(Form)
        self.enter_btn.setGeometry(QtCore.QRect(320, 340, 151, 61))
        self.enter_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.enter_btn.setMouseTracking(False)
        self.enter_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.enter_btn.setObjectName("enter_btn")
        self.teacher_btn = QtWidgets.QPushButton(Form)
        self.teacher_btn.setGeometry(QtCore.QRect(10, 330, 241, 41))
        self.teacher_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.teacher_btn.setMouseTracking(False)
        self.teacher_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.teacher_btn.setObjectName("teacher_btn")
        self.admin_btn = QtWidgets.QPushButton(Form)
        self.admin_btn.setGeometry(QtCore.QRect(10, 380, 241, 41))
        self.admin_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.admin_btn.setMouseTracking(False)
        self.admin_btn.setStyleSheet("QPushButton:hover{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 0, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(12, 0, 185);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"font: 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(112, 193, 255);\n"
"border-radius: 10px;\n"
"}")
        self.admin_btn.setObjectName("admin_btn")
        self.bk_img.raise_()
        self.main_label.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.enter_login.raise_()
        self.enter_password.raise_()
        self.enter_btn.raise_()
        self.teacher_btn.raise_()
        self.admin_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_label.setText(_translate("Form", "Вход"))
        self.label_3.setText(_translate("Form", "Логин:"))
        self.label_4.setText(_translate("Form", "Пароль:"))
        self.enter_btn.setText(_translate("Form", "Войти"))
        self.teacher_btn.setText(_translate("Form", "Войти как учитель"))
        self.admin_btn.setText(_translate("Form", "Я администратор"))
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
