# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teachers_groups.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 573)
        self.name_user = QtWidgets.QLabel(Form)
        self.name_user.setGeometry(QtCore.QRect(50, 20, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.name_user.setFont(font)
        self.name_user.setAlignment(QtCore.Qt.AlignCenter)
        self.name_user.setObjectName("name_user")

        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 70, 371, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 369, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QVBoxLayout()
        self.scrollAreaWidgetContents.setLayout(self.scrollAreaLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(310, 540, 75, 23))
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_user.setText(_translate("Form", "Юлия Сундеева"))
        self.exit_btn.setText(_translate("Form", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
